"""Generate lightpanda/_methods.py from the binary's tools/list schemas.

Emits one concrete, annotated, documented method per browser tool, with the
tool name and its parameters in snake_case, all forwarding to ``Session.call``
(which maps them back to the schema's names). Each docstring carries the tool
description and a Google-style ``Args:`` section from the schema's property
descriptions, so IDEs and pdoc show what every argument means. Being real code, the methods are
visible to IDEs, type checkers, and pdoc alike. Run with a binary available:

    uv run --no-project python scripts/generate_methods.py

CI regenerates and diffs the file to catch tool-schema drift.
"""

from __future__ import annotations

import keyword
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from lightpanda import Browser  # noqa: E402
from lightpanda.browser import _SESSION_TOOLS, _snake  # noqa: E402

PY_TYPES = {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "object": "dict", "array": "list"}

HEADER = '''\
"""Generated by scripts/generate_methods.py — do not edit.

One method per lightpanda browser tool, signatures derived from the tool
JSON schemas, with tool and parameter names in snake_case (the schemas'
camelCase names still work through ``Session.call``). ``AsyncSessionMethods``
is the same surface with ``async def`` signatures.
"""

from __future__ import annotations

from typing import Any
'''

CLASS_HEADER = '''\

class {cls}:
    {prefix}def call(self, tool: str, **kwargs: Any) -> Any:
        raise NotImplementedError
'''


def docstring(description: str, args: list[tuple[str, str]]) -> str:
    """The method docstring: the tool description, then a Google-style
    ``Args:`` section built from the schema's property descriptions."""
    text = description.strip()
    documented = [(arg, desc.strip()) for arg, desc in args if desc.strip()]
    if documented:
        text += "\n\nArgs:\n" + "\n".join(f"    {arg}: {desc}" for arg, desc in documented)
    body = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    lines = body.split("\n")
    if len(lines) == 1:
        return f'        """{body}"""'
    indented = "\n".join(f"        {line}" if line else "" for line in lines)
    return f'        """{indented.lstrip()}\n        """'


def method_source(name: str, spec: dict, is_async: bool = False) -> str:
    schema = spec["schema"]
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    args = {prop: _snake(prop) for prop in properties}
    for prop, arg in args.items():
        if keyword.iskeyword(arg) or not arg.isidentifier():
            raise SystemExit(f"tool {name}: property {prop!r} is not a valid Python parameter")
    if len(set(args.values())) != len(args):
        raise SystemExit(f"tool {name}: properties collide once in snake_case: {sorted(args)}")

    params = ["self"]
    if properties:
        params.append("*")
    forwards = []
    documented = []
    for prop in sorted(properties, key=lambda p: p not in required):
        arg = args[prop]
        py_type = PY_TYPES.get(properties[prop].get("type", ""), "Any")
        if name == "extract" and prop == "schema":
            py_type = "str | dict | list"
        if prop in required:
            params.append(f"{arg}: {py_type}")
        else:
            params.append(f"{arg}: {py_type} | None = None")
        forwards.append(f"{arg}={arg}")
        documented.append((arg, properties[prop].get("description", "")))

    snake = _snake(name)
    call_args = ", ".join([f'"{name}"'] + forwards)
    prefix = "async def" if is_async else "def"
    await_ = "await " if is_async else ""
    lines = [f"    {prefix} {snake}({', '.join(params)}) -> Any:"]
    lines.append(docstring(spec["description"], documented))
    lines.append(f"        return {await_}self.call({call_args})")
    return "\n".join(lines)


def main() -> None:
    out = Path(__file__).parent.parent / "lightpanda" / "_methods.py"
    with Browser() as browser:
        tools = {k: v for k, v in browser.tools.items() if k not in _SESSION_TOOLS}

    blocks = [HEADER]
    for is_async in (False, True):
        cls = "AsyncSessionMethods" if is_async else "SessionMethods"
        blocks.append(CLASS_HEADER.format(cls=cls, prefix="async " if is_async else ""))
        blocks += [method_source(name, tools[name], is_async) for name in sorted(tools)]

    source = "\n".join(blocks) + "\n"
    compile(source, str(out), "exec")
    out.write_text(source)
    print(f"wrote {out} ({len(tools)} tools)")


if __name__ == "__main__":
    main()
